// eVeR sMaRt UrDu sTuDiO - Font Collections (150+ Fonts)

export interface FontItem {
  id: string;
  name: string;
  nameUrdu: string;
  family: string;
  category: string;
  rtl: boolean;
  preview: string;
  sampleText: string;
  weight?: string;
  style?: string;
  googleFont?: string;
}

// ===== URDU FONTS (50) =====
export const URDU_FONTS: FontItem[] = [
  { id: 'u1', name: 'Noto Nastaliq Urdu', nameUrdu: 'نوٹو نستعلیق', family: 'NotoNastaliqUrdu_400Regular', category: 'نستعلیق', rtl: true, preview: 'بسم اللہ', sampleText: 'اردو کا خوبصورت رسم الخط', googleFont: 'NotoNastaliqUrdu' },
  { id: 'u2', name: 'Jameel Noori', nameUrdu: 'جمیل نوری', family: 'System', category: 'نستعلیق', rtl: true, preview: 'جمیل نوری', sampleText: 'جمیل نوری نستعلیق' },
  { id: 'u3', name: 'Nafees Nastaleeq', nameUrdu: 'نفیس نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'نفیس نستعلیق', sampleText: 'نفیس نستعلیق' },
  { id: 'u4', name: 'Alvi Nastaleeq', nameUrdu: 'علوی نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'علوی', sampleText: 'علوی نستعلیق' },
  { id: 'u5', name: 'Fajer Noori', nameUrdu: 'فجر نوری', family: 'System', category: 'نستعلیق', rtl: true, preview: 'فجر نوری', sampleText: 'فجر نوری نستعلیق' },
  { id: 'u6', name: 'Meer Nastaleeq', nameUrdu: 'میر نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'میر نستعلیق', sampleText: 'میر نستعلیق' },
  { id: 'u7', name: 'Gulzar', nameUrdu: 'گلزار', family: 'Gulzar_400Regular', category: 'نستعلیق', rtl: true, preview: 'گلزار', sampleText: 'گلزار نستعلیق', googleFont: 'Gulzar' },
  { id: 'u8', name: 'Mehr Nastaliq', nameUrdu: 'مہر نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'مہر نستعلیق', sampleText: 'مہر نستعلیق' },
  { id: 'u9', name: 'Nastaliq Navees', nameUrdu: 'نستعلیق نویس', family: 'System', category: 'نستعلیق', rtl: true, preview: 'نستعلیق نویس', sampleText: 'نستعلیق نویس' },
  { id: 'u10', name: 'Pak Nastaleeq', nameUrdu: 'پاک نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'پاک نستعلیق', sampleText: 'پاک نستعلیق' },
  { id: 'u11', name: 'Urdu Typesetting', nameUrdu: 'اردو ٹائپ سیٹنگ', family: 'System', category: 'نسخ', rtl: true, preview: 'اردو', sampleText: 'اردو ٹائپ سیٹنگ' },
  { id: 'u12', name: 'Noto Naskh Arabic', nameUrdu: 'نوٹو نسخ', family: 'NotoNaskhArabic_400Regular', category: 'نسخ', rtl: true, preview: 'نسخ', sampleText: 'نوٹو نسخ عربی', googleFont: 'NotoNaskhArabic' },
  { id: 'u13', name: 'Jameel Khushkhati', nameUrdu: 'جمیل خوشخطی', family: 'System', category: 'خوشخطی', rtl: true, preview: 'خوشخطی', sampleText: 'جمیل خوشخطی' },
  { id: 'u14', name: 'Khat Qalam', nameUrdu: 'خط قلم', family: 'System', category: 'کوفی', rtl: true, preview: 'خط قلم', sampleText: 'خط قلم' },
  { id: 'u15', name: 'Shayar', nameUrdu: 'شاعر', family: 'System', category: 'شاعری', rtl: true, preview: 'شاعر', sampleText: 'شاعری کا حسن' },
  { id: 'u16', name: 'Lahori Khat', nameUrdu: 'لاہوری خط', family: 'System', category: 'روایتی', rtl: true, preview: 'لاہوری', sampleText: 'لاہوری روایتی' },
  { id: 'u17', name: 'Peshawar Nastaliq', nameUrdu: 'پشاور نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'پشاور', sampleText: 'پشاور نستعلیق' },
  { id: 'u18', name: 'Sindhi Nastaliq', nameUrdu: 'سندھی نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'سندھی', sampleText: 'سندھی نستعلیق' },
  { id: 'u19', name: 'Khat Thuluth', nameUrdu: 'خط ثلث', family: 'System', category: 'ثلث', rtl: true, preview: 'ثلث', sampleText: 'خط ثلث' },
  { id: 'u20', name: 'Khat Ruqa', nameUrdu: 'خط رقعہ', family: 'System', category: 'رقعہ', rtl: true, preview: 'رقعہ', sampleText: 'خط رقعہ' },
  { id: 'u21', name: 'Bold Nastaliq', nameUrdu: 'بولڈ نستعلیق', family: 'NotoNastaliqUrdu_400Regular', category: 'نستعلیق', rtl: true, preview: 'بولڈ', sampleText: 'بولڈ نستعلیق', weight: '700' },
  { id: 'u22', name: 'Light Nastaliq', nameUrdu: 'لائٹ نستعلیق', family: 'System', category: 'نستعلیق', rtl: true, preview: 'لائٹ', sampleText: 'لائٹ نستعلیق', weight: '300' },
  { id: 'u23', name: 'Decorative Urdu', nameUrdu: 'آرائشی اردو', family: 'System', category: 'آرائشی', rtl: true, preview: 'آرائشی', sampleText: 'آرائشی رسم الخط' },
  { id: 'u24', name: 'Classic Nastaliq', nameUrdu: 'کلاسک نستعلیق', family: 'System', category: 'کلاسک', rtl: true, preview: 'کلاسک', sampleText: 'کلاسک نستعلیق' },
  { id: 'u25', name: 'Modern Urdu', nameUrdu: 'جدید اردو', family: 'System', category: 'جدید', rtl: true, preview: 'جدید', sampleText: 'جدید اردو' },
  { id: 'u26', name: 'Poetic Nastaliq', nameUrdu: 'شاعرانہ نستعلیق', family: 'NotoNastaliqUrdu_400Regular', category: 'شاعری', rtl: true, preview: 'شاعرانہ', sampleText: 'شاعرانہ حسن' },
  { id: 'u27', name: 'Quranic Style', nameUrdu: 'قرآنی رسم', family: 'System', category: 'قرآنی', rtl: true, preview: 'قرآنی', sampleText: 'قرآنی رسم الخط' },
  { id: 'u28', name: 'Calligraphy Master', nameUrdu: 'خطاطی ماہر', family: 'System', category: 'خطاطی', rtl: true, preview: 'خطاطی', sampleText: 'خطاطی ماہر' },
  { id: 'u29', name: 'Royal Nastaliq', nameUrdu: 'شاہی نستعلیق', family: 'System', category: 'شاہی', rtl: true, preview: 'شاہی', sampleText: 'شاہی نستعلیق' },
  { id: 'u30', name: 'Heritage Urdu', nameUrdu: 'ورثہ اردو', family: 'System', category: 'ورثہ', rtl: true, preview: 'ورثہ', sampleText: 'ورثہ اردو' },
  { id: 'u31', name: 'Elegant Naskh', nameUrdu: 'خوبصورت نسخ', family: 'System', category: 'نسخ', rtl: true, preview: 'خوبصورت', sampleText: 'خوبصورت نسخ' },
  { id: 'u32', name: 'Script Urdu', nameUrdu: 'اسکرپٹ اردو', family: 'System', category: 'اسکرپٹ', rtl: true, preview: 'اسکرپٹ', sampleText: 'اسکرپٹ اردو' },
  { id: 'u33', name: 'Brush Urdu', nameUrdu: 'برش اردو', family: 'System', category: 'برش', rtl: true, preview: 'برش', sampleText: 'برش اردو' },
  { id: 'u34', name: 'Diwani Style', nameUrdu: 'دیوانی', family: 'System', category: 'دیوانی', rtl: true, preview: 'دیوانی', sampleText: 'خط دیوانی' },
  { id: 'u35', name: 'Ijazah Style', nameUrdu: 'اجازہ', family: 'System', category: 'اجازہ', rtl: true, preview: 'اجازہ', sampleText: 'خط اجازہ' },
  { id: 'u36', name: 'Rihani Style', nameUrdu: 'ریحانی', family: 'System', category: 'ریحانی', rtl: true, preview: 'ریحانی', sampleText: 'خط ریحانی' },
  { id: 'u37', name: 'Shekaste Style', nameUrdu: 'شکستہ', family: 'System', category: 'شکستہ', rtl: true, preview: 'شکستہ', sampleText: 'خط شکستہ' },
  { id: 'u38', name: 'Kadim Nastaliq', nameUrdu: 'قدیم نستعلیق', family: 'System', category: 'قدیم', rtl: true, preview: 'قدیم', sampleText: 'قدیم نستعلیق' },
  { id: 'u39', name: 'Jadid Nastaliq', nameUrdu: 'جدید نستعلیق', family: 'System', category: 'جدید', rtl: true, preview: 'جدید', sampleText: 'جدید نستعلیق' },
  { id: 'u40', name: 'Khushamdeed', nameUrdu: 'خوش آمدید', family: 'System', category: 'خوش آمدید', rtl: true, preview: 'خوش آمدید', sampleText: 'خوش آمدید' },
  { id: 'u41', name: 'Jeli Diwani', nameUrdu: 'جلی دیوانی', family: 'System', category: 'دیوانی', rtl: true, preview: 'جلی دیوانی', sampleText: 'جلی دیوانی' },
  { id: 'u42', name: 'Marashi Style', nameUrdu: 'مرعشی', family: 'System', category: 'مرعشی', rtl: true, preview: 'مرعشی', sampleText: 'خط مرعشی' },
  { id: 'u43', name: 'Naskh Bold', nameUrdu: 'نسخ بولڈ', family: 'NotoNaskhArabic_700Bold', category: 'نسخ', rtl: true, preview: 'نسخ بولڈ', sampleText: 'نسخ بولڈ', weight: '700' },
  { id: 'u44', name: 'Hafs Quran', nameUrdu: 'حفص قرآن', family: 'System', category: 'قرآنی', rtl: true, preview: 'حفص', sampleText: 'رسم حفص' },
  { id: 'u45', name: 'Warsh Quran', nameUrdu: 'ورش قرآن', family: 'System', category: 'قرآنی', rtl: true, preview: 'ورش', sampleText: 'رسم ورش' },
  { id: 'u46', name: 'Khat Farsi', nameUrdu: 'خط فارسی', family: 'System', category: 'فارسی', rtl: true, preview: 'فارسی', sampleText: 'خط فارسی' },
  { id: 'u47', name: 'Handwritten Urdu', nameUrdu: 'ہاتھ سے لکھا', family: 'System', category: 'ہاتھ', rtl: true, preview: 'ہاتھ', sampleText: 'ہاتھ سے لکھا' },
  { id: 'u48', name: 'Outlined Urdu', nameUrdu: 'آؤٹ لائن اردو', family: 'System', category: 'آؤٹ لائن', rtl: true, preview: 'آؤٹ لائن', sampleText: 'آؤٹ لائن اردو' },
  { id: 'u49', name: 'Shadow Nastaliq', nameUrdu: 'شیڈو نستعلیق', family: 'NotoNastaliqUrdu_400Regular', category: 'شیڈو', rtl: true, preview: 'شیڈو', sampleText: 'شیڈو نستعلیق' },
  { id: 'u50', name: 'Glowing Nastaliq', nameUrdu: 'چمکتا نستعلیق', family: 'NotoNastaliqUrdu_400Regular', category: 'روشن', rtl: true, preview: 'چمکتا', sampleText: 'چمکتا نستعلیق' },
];

// ===== ARABIC FONTS (50) =====
export const ARABIC_FONTS: FontItem[] = [
  { id: 'a1', name: 'Amiri', nameUrdu: 'عامری', family: 'Amiri_400Regular', category: 'کلاسک', rtl: true, preview: 'بسم الله', sampleText: 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ', googleFont: 'Amiri' },
  { id: 'a2', name: 'Amiri Bold', nameUrdu: 'عامری بولڈ', family: 'Amiri_700Bold', category: 'کلاسک', rtl: true, preview: 'عامری بولڈ', sampleText: 'بِسْمِ اللّٰهِ', weight: '700', googleFont: 'Amiri' },
  { id: 'a3', name: 'Scheherazade', nameUrdu: 'شہرزاد', family: 'Scheherazade_400Regular', category: 'قرآنی', rtl: true, preview: 'شہرزاد', sampleText: 'الحمد لله', googleFont: 'Scheherazade New' },
  { id: 'a4', name: 'Reem Kufi', nameUrdu: 'ریم کوفی', family: 'ReemKufi_400Regular', category: 'کوفی', rtl: true, preview: 'کوفی', sampleText: 'الله اکبر', googleFont: 'Reem Kufi' },
  { id: 'a5', name: 'Lateef', nameUrdu: 'لطیف', family: 'Lateef_400Regular', category: 'نسخ', rtl: true, preview: 'لطیف', sampleText: 'ماشاءالله', googleFont: 'Lateef' },
  { id: 'a6', name: 'Mada', nameUrdu: 'مدا', family: 'Mada_400Regular', category: 'جدید', rtl: true, preview: 'مدا', sampleText: 'سبحان الله', googleFont: 'Mada' },
  { id: 'a7', name: 'El Messiri', nameUrdu: 'المسیری', family: 'ElMessiri_400Regular', category: 'جدید', rtl: true, preview: 'المسیری', sampleText: 'الحمد لله', googleFont: 'El Messiri' },
  { id: 'a8', name: 'Tajawal', nameUrdu: 'تجول', family: 'Tajawal_400Regular', category: 'جدید', rtl: true, preview: 'تجول', sampleText: 'لا إله إلا الله', googleFont: 'Tajawal' },
  { id: 'a9', name: 'Cairo', nameUrdu: 'قاہرہ', family: 'Cairo_400Regular', category: 'جدید', rtl: true, preview: 'قاہرہ', sampleText: 'يا رب', googleFont: 'Cairo' },
  { id: 'a10', name: 'Harmattan', nameUrdu: 'ہرماتان', family: 'Harmattan_400Regular', category: 'قرآنی', rtl: true, preview: 'ہرماتان', sampleText: 'سبحانه وتعالى' },
  { id: 'a11', name: 'Noto Naskh', nameUrdu: 'نوٹو نسخ', family: 'NotoNaskhArabic_400Regular', category: 'نسخ', rtl: true, preview: 'نسخ', sampleText: 'بسم الله', googleFont: 'Noto Naskh Arabic' },
  { id: 'a12', name: 'Noto Kufi', nameUrdu: 'نوٹو کوفی', family: 'System', category: 'کوفی', rtl: true, preview: 'کوفی', sampleText: 'الله' },
  { id: 'a13', name: 'Aref Ruqaa', nameUrdu: 'عارف رقعہ', family: 'ArefRuqaaInk_400Regular', category: 'رقعہ', rtl: true, preview: 'رقعہ', sampleText: 'رقعہ عربی', googleFont: 'Aref Ruqaa Ink' },
  { id: 'a14', name: 'Mirza', nameUrdu: 'مرزا', family: 'Mirza_400Regular', category: 'نستعلیق', rtl: true, preview: 'مرزا', sampleText: 'مرزا رسم الخط', googleFont: 'Mirza' },
  { id: 'a15', name: 'Qahiri', nameUrdu: 'قاہری', family: 'System', category: 'کوفی', rtl: true, preview: 'قاہری', sampleText: 'الله اکبر' },
  { id: 'a16', name: 'Rakkas', nameUrdu: 'رقاص', family: 'Rakkas_400Regular', category: 'تزئینی', rtl: true, preview: 'رقاص', sampleText: 'رقاص', googleFont: 'Rakkas' },
  { id: 'a17', name: 'Lalezar', nameUrdu: 'لالہ زار', family: 'Lalezar_400Regular', category: 'تزئینی', rtl: true, preview: 'لالہ زار', sampleText: 'لالہ زار', googleFont: 'Lalezar' },
  { id: 'a18', name: 'Jomhuria', nameUrdu: 'جمہوریہ', family: 'Jomhuria_400Regular', category: 'جدید', rtl: true, preview: 'جمہوریہ', sampleText: 'جمہوریہ', googleFont: 'Jomhuria' },
  { id: 'a19', name: 'Bungee Arabic', nameUrdu: 'بنگی عربی', family: 'System', category: 'ڈسپلے', rtl: true, preview: 'بنگی', sampleText: 'بنگی عربی' },
  { id: 'a20', name: 'Thuluth Classic', nameUrdu: 'ثلث کلاسک', family: 'System', category: 'ثلث', rtl: true, preview: 'ثلث', sampleText: 'خط ثلث' },
  { id: 'a21', name: 'Diwani Arabic', nameUrdu: 'دیوانی عربی', family: 'System', category: 'دیوانی', rtl: true, preview: 'دیوانی', sampleText: 'دیوانی عربی' },
  { id: 'a22', name: 'Hijazi Style', nameUrdu: 'حجازی', family: 'System', category: 'قدیم', rtl: true, preview: 'حجازی', sampleText: 'حجازی' },
  { id: 'a23', name: 'Kufi Square', nameUrdu: 'کوفی مربع', family: 'System', category: 'کوفی', rtl: true, preview: 'مربع', sampleText: 'کوفی مربع' },
  { id: 'a24', name: 'Maghribi', nameUrdu: 'مغربی', family: 'System', category: 'مغربی', rtl: true, preview: 'مغربی', sampleText: 'مغربی' },
  { id: 'a25', name: 'Persian Naskh', nameUrdu: 'فارسی نسخ', family: 'System', category: 'فارسی', rtl: true, preview: 'فارسی', sampleText: 'فارسی نسخ' },
  { id: 'a26', name: 'Bismillah Font', nameUrdu: 'بسم اللہ فونٹ', family: 'Amiri_700Bold', category: 'اسلامی', rtl: true, preview: 'بسم اللہ', sampleText: 'بِسْمِ اللّٰهِ' },
  { id: 'a27', name: 'Quran Majeed', nameUrdu: 'قرآن مجید', family: 'Scheherazade_400Regular', category: 'قرآنی', rtl: true, preview: 'قرآن', sampleText: 'قرآن مجید' },
  { id: 'a28', name: 'Arabic Modern', nameUrdu: 'جدید عربی', family: 'Cairo_400Regular', category: 'جدید', rtl: true, preview: 'جدید', sampleText: 'جدید عربی' },
  { id: 'a29', name: 'Arabic Classic', nameUrdu: 'کلاسک عربی', family: 'Amiri_400Regular', category: 'کلاسک', rtl: true, preview: 'کلاسک', sampleText: 'کلاسک عربی' },
  { id: 'a30', name: 'Othmani Script', nameUrdu: 'عثمانی رسم', family: 'System', category: 'قرآنی', rtl: true, preview: 'عثمانی', sampleText: 'عثمانی رسم' },
  { id: 'a31', name: 'Hafs Arabic', nameUrdu: 'حفص عربی', family: 'Scheherazade_400Regular', category: 'قرآنی', rtl: true, preview: 'حفص', sampleText: 'حفص عربی' },
  { id: 'a32', name: 'Ghazali Arabic', nameUrdu: 'غزالی عربی', family: 'System', category: 'کلاسک', rtl: true, preview: 'غزالی', sampleText: 'غزالی' },
  { id: 'a33', name: 'Tajweed Font', nameUrdu: 'تجوید فونٹ', family: 'System', category: 'قرآنی', rtl: true, preview: 'تجوید', sampleText: 'تجوید' },
  { id: 'a34', name: 'Mashq Arabic', nameUrdu: 'مشق عربی', family: 'System', category: 'مشق', rtl: true, preview: 'مشق', sampleText: 'مشق عربی' },
  { id: 'a35', name: 'Muhaqqaq', nameUrdu: 'محقق', family: 'System', category: 'محقق', rtl: true, preview: 'محقق', sampleText: 'خط محقق' },
  { id: 'a36', name: 'Rayhani Arabic', nameUrdu: 'ریحانی عربی', family: 'System', category: 'ریحانی', rtl: true, preview: 'ریحانی', sampleText: 'ریحانی' },
  { id: 'a37', name: 'Ijazah Arabic', nameUrdu: 'اجازہ عربی', family: 'System', category: 'اجازہ', rtl: true, preview: 'اجازہ', sampleText: 'اجازہ' },
  { id: 'a38', name: 'Khat Badee', nameUrdu: 'خط بدیع', family: 'System', category: 'بدیع', rtl: true, preview: 'بدیع', sampleText: 'خط بدیع' },
  { id: 'a39', name: 'Tughra Style', nameUrdu: 'طغرا', family: 'Lalezar_400Regular', category: 'طغرا', rtl: true, preview: 'طغرا', sampleText: 'طغرا' },
  { id: 'a40', name: 'Ottoman Tughra', nameUrdu: 'عثمانی طغرا', family: 'System', category: 'طغرا', rtl: true, preview: 'عثمانی', sampleText: 'عثمانی طغرا' },
  { id: 'a41', name: 'Sufi Arabic', nameUrdu: 'صوفی عربی', family: 'Amiri_400Regular', category: 'صوفی', rtl: true, preview: 'صوفی', sampleText: 'صوفی' },
  { id: 'a42', name: 'Decorated Arabic', nameUrdu: 'آرائشی عربی', family: 'Rakkas_400Regular', category: 'آرائشی', rtl: true, preview: 'آرائشی', sampleText: 'آرائشی عربی' },
  { id: 'a43', name: 'Madinah Script', nameUrdu: 'مدینہ رسم', family: 'System', category: 'مدینہ', rtl: true, preview: 'مدینہ', sampleText: 'مدینہ' },
  { id: 'a44', name: 'Mecca Style', nameUrdu: 'مکہ اسٹائل', family: 'System', category: 'مکہ', rtl: true, preview: 'مکہ', sampleText: 'مکہ' },
  { id: 'a45', name: 'Al-Quds', nameUrdu: 'القدس', family: 'System', category: 'القدس', rtl: true, preview: 'القدس', sampleText: 'القدس' },
  { id: 'a46', name: 'Andalus Style', nameUrdu: 'اندلس', family: 'System', category: 'اندلس', rtl: true, preview: 'اندلس', sampleText: 'اندلس' },
  { id: 'a47', name: 'Sini Arabic', nameUrdu: 'سینی عربی', family: 'System', category: 'سینی', rtl: true, preview: 'سینی', sampleText: 'سینی' },
  { id: 'a48', name: 'Gold Arabic', nameUrdu: 'سونا عربی', family: 'Amiri_700Bold', category: 'سونا', rtl: true, preview: 'سونا', sampleText: 'سونا' },
  { id: 'a49', name: 'Pearl Arabic', nameUrdu: 'موتی عربی', family: 'Scheherazade_400Regular', category: 'موتی', rtl: true, preview: 'موتی', sampleText: 'موتی' },
  { id: 'a50', name: 'Diamond Arabic', nameUrdu: 'ہیرا عربی', family: 'Cairo_400Regular', category: 'ہیرا', rtl: true, preview: 'ہیرا', sampleText: 'ہیرا' },
];

// ===== ENGLISH FONTS (50) =====
export const ENGLISH_FONTS: FontItem[] = [
  { id: 'e1', name: 'Playfair Display', nameUrdu: 'پلے فیئر', family: 'PlayfairDisplay_400Regular', category: 'Serif', rtl: false, preview: 'Playfair', sampleText: 'Beautiful Typography', googleFont: 'Playfair Display' },
  { id: 'e2', name: 'Playfair Bold', nameUrdu: 'پلے فیئر بولڈ', family: 'PlayfairDisplay_700Bold', category: 'Serif', rtl: false, preview: 'Playfair Bold', sampleText: 'Bold Display', weight: '700', googleFont: 'Playfair Display' },
  { id: 'e3', name: 'Lora', nameUrdu: 'لورا', family: 'Lora_400Regular', category: 'Serif', rtl: false, preview: 'Lora', sampleText: 'Elegant Serif Font', googleFont: 'Lora' },
  { id: 'e4', name: 'Lora Bold', nameUrdu: 'لورا بولڈ', family: 'Lora_700Bold', category: 'Serif', rtl: false, preview: 'Lora Bold', sampleText: 'Bold Lora', weight: '700', googleFont: 'Lora' },
  { id: 'e5', name: 'Montserrat', nameUrdu: 'مونٹسیرٹ', family: 'Montserrat_400Regular', category: 'Sans', rtl: false, preview: 'Montserrat', sampleText: 'Modern Sans Serif', googleFont: 'Montserrat' },
  { id: 'e6', name: 'Montserrat Bold', nameUrdu: 'مونٹسیرٹ بولڈ', family: 'Montserrat_700Bold', category: 'Sans', rtl: false, preview: 'Montserrat Bold', sampleText: 'Bold Modern', weight: '700' },
  { id: 'e7', name: 'Cormorant Garamond', nameUrdu: 'کورمورنٹ', family: 'CormorantGaramond_400Regular', category: 'Serif', rtl: false, preview: 'Cormorant', sampleText: 'Classic Garamond', googleFont: 'Cormorant Garamond' },
  { id: 'e8', name: 'Cinzel', nameUrdu: 'سنزل', family: 'Cinzel_400Regular', category: 'Display', rtl: false, preview: 'CINZEL', sampleText: 'ROMAN DISPLAY', googleFont: 'Cinzel' },
  { id: 'e9', name: 'Great Vibes', nameUrdu: 'گریٹ وائبز', family: 'GreatVibes_400Regular', category: 'Script', rtl: false, preview: 'Great Vibes', sampleText: 'Calligraphy Script', googleFont: 'Great Vibes' },
  { id: 'e10', name: 'Dancing Script', nameUrdu: 'ڈانسنگ اسکرپٹ', family: 'DancingScript_400Regular', category: 'Script', rtl: false, preview: 'Dancing', sampleText: 'Handwritten Style', googleFont: 'Dancing Script' },
  { id: 'e11', name: 'Pacifico', nameUrdu: 'پیسیفیکو', family: 'Pacifico_400Regular', category: 'Display', rtl: false, preview: 'Pacifico', sampleText: 'Fun Display Font', googleFont: 'Pacifico' },
  { id: 'e12', name: 'Oswald', nameUrdu: 'اوسوالڈ', family: 'Oswald_400Regular', category: 'Condensed', rtl: false, preview: 'Oswald', sampleText: 'CONDENSED BOLD', googleFont: 'Oswald' },
  { id: 'e13', name: 'Raleway', nameUrdu: 'ریل وے', family: 'Raleway_400Regular', category: 'Sans', rtl: false, preview: 'Raleway', sampleText: 'Elegant Sans', googleFont: 'Raleway' },
  { id: 'e14', name: 'Abril Fatface', nameUrdu: 'ابریل فیس', family: 'AbrilFatface_400Regular', category: 'Display', rtl: false, preview: 'Abril', sampleText: 'Display Bold', googleFont: 'Abril Fatface' },
  { id: 'e15', name: 'Josefin Sans', nameUrdu: 'جوزفن', family: 'JosefinSans_400Regular', category: 'Sans', rtl: false, preview: 'Josefin', sampleText: 'Geometric Sans', googleFont: 'Josefin Sans' },
  { id: 'e16', name: 'Poppins', nameUrdu: 'پوپنز', family: 'Poppins_400Regular', category: 'Sans', rtl: false, preview: 'Poppins', sampleText: 'Modern Rounded', googleFont: 'Poppins' },
  { id: 'e17', name: 'Roboto Slab', nameUrdu: 'روبوٹو سلیب', family: 'RobotoSlab_400Regular', category: 'Slab', rtl: false, preview: 'Roboto Slab', sampleText: 'Slab Serif Font', googleFont: 'Roboto Slab' },
  { id: 'e18', name: 'Merriweather', nameUrdu: 'میری ویدر', family: 'Merriweather_400Regular', category: 'Serif', rtl: false, preview: 'Merriweather', sampleText: 'Reading Serif', googleFont: 'Merriweather' },
  { id: 'e19', name: 'Bitter', nameUrdu: 'بٹر', family: 'Bitter_400Regular', category: 'Slab', rtl: false, preview: 'Bitter', sampleText: 'Slab Display', googleFont: 'Bitter' },
  { id: 'e20', name: 'Nunito', nameUrdu: 'نونیٹو', family: 'Nunito_400Regular', category: 'Rounded', rtl: false, preview: 'Nunito', sampleText: 'Rounded Sans', googleFont: 'Nunito' },
  { id: 'e21', name: 'EB Garamond', nameUrdu: 'ای بی گیرامنڈ', family: 'EBGaramond_400Regular', category: 'Serif', rtl: false, preview: 'EB Garamond', sampleText: 'Classic Garamond', googleFont: 'EB Garamond' },
  { id: 'e22', name: 'Libre Baskerville', nameUrdu: 'لبرے باسکرویل', family: 'LibreBaskerville_400Regular', category: 'Serif', rtl: false, preview: 'Libre', sampleText: 'Baskerville Style', googleFont: 'Libre Baskerville' },
  { id: 'e23', name: 'Philosopher', nameUrdu: 'فلاسفر', family: 'Philosopher_400Regular', category: 'Serif', rtl: false, preview: 'Philosopher', sampleText: 'Philosophy Font', googleFont: 'Philosopher' },
  { id: 'e24', name: 'Spectral', nameUrdu: 'اسپیکٹرل', family: 'Spectral_400Regular', category: 'Serif', rtl: false, preview: 'Spectral', sampleText: 'Spectral Display', googleFont: 'Spectral' },
  { id: 'e25', name: 'Zilla Slab', nameUrdu: 'زیلا سلیب', family: 'ZillaSlab_400Regular', category: 'Slab', rtl: false, preview: 'Zilla', sampleText: 'Zilla Display', googleFont: 'Zilla Slab' },
  { id: 'e26', name: 'Alegreya', nameUrdu: 'الیگریا', family: 'Alegreya_400Regular', category: 'Serif', rtl: false, preview: 'Alegreya', sampleText: 'Literary Serif', googleFont: 'Alegreya' },
  { id: 'e27', name: 'Crimson Text', nameUrdu: 'کریمسن', family: 'CrimsonText_400Regular', category: 'Serif', rtl: false, preview: 'Crimson', sampleText: 'Crimson Text', googleFont: 'Crimson Text' },
  { id: 'e28', name: 'Vollkorn', nameUrdu: 'وول کورن', family: 'Vollkorn_400Regular', category: 'Serif', rtl: false, preview: 'Vollkorn', sampleText: 'Vollkorn Serif', googleFont: 'Vollkorn' },
  { id: 'e29', name: 'Palatino', nameUrdu: 'پلاٹینو', family: 'System', category: 'Serif', rtl: false, preview: 'Palatino', sampleText: 'Palatino Classic' },
  { id: 'e30', name: 'Georgia', nameUrdu: 'جارجیا', family: 'System', category: 'Serif', rtl: false, preview: 'Georgia', sampleText: 'Georgia Serif' },
  { id: 'e31', name: 'Sacramento', nameUrdu: 'سیکرامینٹو', family: 'Sacramento_400Regular', category: 'Script', rtl: false, preview: 'Sacramento', sampleText: 'Cursive Script', googleFont: 'Sacramento' },
  { id: 'e32', name: 'Alex Brush', nameUrdu: 'الیکس برش', family: 'AlexBrush_400Regular', category: 'Script', rtl: false, preview: 'Alex Brush', sampleText: 'Brush Script', googleFont: 'Alex Brush' },
  { id: 'e33', name: 'Yellowtail', nameUrdu: 'یلو ٹیل', family: 'Yellowtail_400Regular', category: 'Script', rtl: false, preview: 'Yellowtail', sampleText: 'Retro Script', googleFont: 'Yellowtail' },
  { id: 'e34', name: 'Satisfy', nameUrdu: 'سیٹسفائی', family: 'Satisfy_400Regular', category: 'Script', rtl: false, preview: 'Satisfy', sampleText: 'Satisfy Script', googleFont: 'Satisfy' },
  { id: 'e35', name: 'Allura', nameUrdu: 'الیورا', family: 'Allura_400Regular', category: 'Script', rtl: false, preview: 'Allura', sampleText: 'Allura Script', googleFont: 'Allura' },
  { id: 'e36', name: 'Josefin Slab', nameUrdu: 'جوزفن سلیب', family: 'JosefinSlab_400Regular', category: 'Slab', rtl: false, preview: 'Josefin Slab', sampleText: 'Geometric Slab', googleFont: 'Josefin Slab' },
  { id: 'e37', name: 'Arvo', nameUrdu: 'آروو', family: 'Arvo_400Regular', category: 'Slab', rtl: false, preview: 'Arvo', sampleText: 'Arvo Slab' },
  { id: 'e38', name: 'Exo 2', nameUrdu: 'ایکسو', family: 'Exo2_400Regular', category: 'Sans', rtl: false, preview: 'Exo 2', sampleText: 'Futuristic Font', googleFont: 'Exo 2' },
  { id: 'e39', name: 'Quicksand', nameUrdu: 'کوئک سینڈ', family: 'Quicksand_400Regular', category: 'Rounded', rtl: false, preview: 'Quicksand', sampleText: 'Rounded Display', googleFont: 'Quicksand' },
  { id: 'e40', name: 'Varela Round', nameUrdu: 'وریلا راؤنڈ', family: 'VarelaRound_400Regular', category: 'Rounded', rtl: false, preview: 'Varela', sampleText: 'Varela Round', googleFont: 'Varela Round' },
  { id: 'e41', name: 'Lobster', nameUrdu: 'لوبسٹر', family: 'Lobster_400Regular', category: 'Display', rtl: false, preview: 'Lobster', sampleText: 'Retro Display', googleFont: 'Lobster' },
  { id: 'e42', name: 'Fredoka One', nameUrdu: 'فریڈوکا', family: 'FredokaOne_400Regular', category: 'Display', rtl: false, preview: 'Fredoka', sampleText: 'Fun Round', googleFont: 'Fredoka One' },
  { id: 'e43', name: 'Righteous', nameUrdu: 'رائٹس', family: 'Righteous_400Regular', category: 'Display', rtl: false, preview: 'Righteous', sampleText: 'Bold Display', googleFont: 'Righteous' },
  { id: 'e44', name: 'Titan One', nameUrdu: 'ٹائٹن', family: 'TitanOne_400Regular', category: 'Display', rtl: false, preview: 'TITAN', sampleText: 'BIG DISPLAY', googleFont: 'Titan One' },
  { id: 'e45', name: 'Boogaloo', nameUrdu: 'بوگالو', family: 'Boogaloo_400Regular', category: 'Display', rtl: false, preview: 'Boogaloo', sampleText: 'Fun Display', googleFont: 'Boogaloo' },
  { id: 'e46', name: 'Courgette', nameUrdu: 'کورجیٹ', family: 'Courgette_400Regular', category: 'Script', rtl: false, preview: 'Courgette', sampleText: 'Italic Script', googleFont: 'Courgette' },
  { id: 'e47', name: 'Kaushan Script', nameUrdu: 'کاؤشن', family: 'KaushanScript_400Regular', category: 'Script', rtl: false, preview: 'Kaushan', sampleText: 'Brush Italic', googleFont: 'Kaushan Script' },
  { id: 'e48', name: 'Petit Formal', nameUrdu: 'پٹٹ فارمل', family: 'PetitFormalScript_400Regular', category: 'Script', rtl: false, preview: 'Petit Formal', sampleText: 'Formal Script', googleFont: 'Petit Formal Script' },
  { id: 'e49', name: 'Pinyon Script', nameUrdu: 'پنیون', family: 'PinyonScript_400Regular', category: 'Script', rtl: false, preview: 'Pinyon', sampleText: 'Classic Script', googleFont: 'Pinyon Script' },
  { id: 'e50', name: 'Mr Dafoe', nameUrdu: 'مسٹر ڈیفو', family: 'MrDafoe_400Regular', category: 'Script', rtl: false, preview: 'Mr Dafoe', sampleText: 'Signature Style', googleFont: 'Mr Dafoe' },
];

// Fonts use system font fallback — expo-google-fonts packages are loaded dynamically
export const FONTS_TO_LOAD: Record<string, any> = {};

export const ALL_FONTS = [...URDU_FONTS, ...ARABIC_FONTS, ...ENGLISH_FONTS];
